config/routes.rb
Rails.application.routes.draw do
  get 'plays/your_turn'

  get 'plays/cpu_turn'

  get 'plays/result'

  get 'plays/start_game'

  get 'plays/start_event'

  get 'plays/your_request'

  get 'plays/cpu_request'

  resources :cards
  root 'pages#home'

  get 'pages/play'

  get 'pages/start_event'

end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:url, :tipo, :nome, :forca, :velocidade, :habilidade, :equipamento, :inteligencia)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def play
  end

  def newCarta
  end

end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def your_turn
  end

  def cpu_turn
  end

  def result
  end

  def start_game
  end

  #start the game
  def start_event
    #create global arrays
    $playerMount = Array.new
    $cpuMount = Array.new

    #divide the deck in two mounts
    Card.all.each do |card|
      if $playerMount.length < 15 && $cpuMount.length < 15
        if (rand(1...10) % 2) == 0
          $playerMount.push(card)
        else
          $cpuMount.push(card)
        end
      else
        if $playerMount.length == 15
          $cpuMount.push(card)
        else
          $playerMount.push(card)
        end
      end
    end

    #shuffle both mounts
    $playerMount = $playerMount.shuffle
    $cpuMount = $cpuMount.shuffle

  end
  helper_method :start_event

  #compare your card with the cpu card
  def your_request
    $your_card = $playerMount.first
    $cpu_card = $cpuMount.first
    if $playerMount.first.forca < $cpuMount.first.forca
      $cpuMount.delete($cpuMount.first)
      $playerMount.delete($playerMount.first)
      $cpuMount.push($your_card)
      $cpuMount.push($cpu_card)
    else
      $playerMount.delete($playerMount.first)
      $cpuMount.delete($cpuMount.first)
      $playerMount.push($cpu_card)
      $playerMount.push($your_card)
    end
  end
  helper_method :your_request

  #compare cpu card with your card
  def cpu_request
    $your_card = $playerMount.first
    $cpu_card = $cpuMount.first
    if $playerMount.first.velocidade < $cpuMount.first.velocidade
      $cpuMount.delete($cpuMount.first)
      $playerMount.delete($playerMount.first)
      $cpuMount.push($your_card)
      $cpuMount.push($cpu_card)
    else
      $playerMount.delete($playerMount.first)
      $cpuMount.delete($cpuMount.first)
      $playerMount.push($cpu_card)
      $playerMount.push($your_card)
    end
  end
  helper_method :cpu_request

  #register your turn
  def you_play
    $myTurn = true
    $myTurn
  end
  helper_method :you_play

  #register cpu's turn
  def cpu_plays
    $myTurn = false
    $myTurn
  end
  helper_method :cpu_plays


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :forca %><br>
    <%= f.number_field :forca %>
  </div>
  <div class="field">
    <%= f.label :velocidade %><br>
    <%= f.number_field :velocidade %>
  </div>
  <div class="field">
    <%= f.label :habilidade %><br>
    <%= f.number_field :habilidade %>
  </div>
  <div class="field">
    <%= f.label :equipamento %><br>
    <%= f.number_field :equipamento %>
  </div>
  <div class="field">
    <%= f.label :inteligencia %><br>
    <%= f.number_field :inteligencia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table>
  <thead>
    <tr>
      <!-- <th>Url</th> -->
      <th>Tipo</th>
      <th>Nome</th>
      <th>Forca</th>
      <th>Velocidade</th>
      <th>Habilidade</th>
      <th>Equipamento</th>
      <th>Inteligencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <!-- <td><%= card.url %></td> -->
        <td><%= card.tipo %></td>
        <td><%= card.nome %></td>
        <td><%= card.forca %></td>
        <td><%= card.velocidade %></td>
        <td><%= card.habilidade %></td>
        <td><%= card.equipamento %></td>
        <td><%= card.inteligencia %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<div style="float:left">

<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @card.url %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @card.tipo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @card.nome %>
</p>

<p>
  <strong>Forca:</strong>
  <%= @card.forca %>
</p>

<p>
  <strong>Velocidade:</strong>
  <%= @card.velocidade %>
</p>

<p>
  <strong>Habilidade:</strong>
  <%= @card.habilidade %>
</p>

<p>
  <strong>Equipamento:</strong>
  <%= @card.equipamento %>
</p>

<p>
  <strong>Inteligencia:</strong>
  <%= @card.inteligencia %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

</div>

<div style="float:left; margin-left: 50px">
  <p>
    <%= image_tag(@card.url, width: '300') %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperTrunfo2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>

  <div class="header">
  <div class="menu">
    <div class="option">
      <a href="/">Home</a>
    </div>
    <div class="option">
      <a href="/plays/start_game">Play</a>
    </div>
    <div class="option">
      <a href="/cards/">New cards</a>
    </div>
    <div class="option">
      <a href="#">More options</a>
    </div>
  </div>
</div>

<%= yield %>


</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/newCarta.html.erb
<h1>Pages#newCarta</h1>
<p>Find me in app/views/pages/newCarta.html.erb</p>

app/views/pages/play.html.erb
<p style="margin: 50px 30px">
<% start_event %>
<button type="button" name="button" id="start">Start Game</button>


</p>


<div id="your_hand" style="width: 50%; text-align: center; float: left">
<h2>You</h2>
<p>
  <% if get_playerMount.empty? == false %>
  <%= image_tag(@get_playerMount.first.url, width: '300') %>
  <br>
  <%= label("", "Força") %>
  <%= radio_button("card", "", get_playerMount.first.forca) %>
  <%= label("", "Velocidade") %>
  <%= radio_button("card", "", get_playerMount.first.velocidade) %>
  <%= label("", "Habilidade") %>
  <%= radio_button("card", "", get_playerMount.first.habilidade) %>
  <%= label("", "Equipamento") %>
  <%= radio_button("card", "", get_playerMount.first.equipamento) %>
  <%= label("", "Inteligência") %>
  <%= radio_button("card", "", get_playerMount.first.inteligencia) %>

  <% end %>
</p>

</div>

<div id="cpu_hand" style="width: 50%; text-align: center; float: left">
  <h2>CPU</h2>
  <p>
    <% if get_cpuMount.empty? == false %>
    <%= image_tag(@get_cpuMount.first.url, width: '300') %>

    <% end %>
  </p>
</div>


<script type="text/javascript">
$('#your_hand').hide();
$('#cpu_hand').hide();
$.ajax({
    url:'/pages/start_event',
    type:'PUT'

  });


$('#start').click(function(){
  $('#your_hand').show();
  $('#cpu_hand').show();
  // $('#start').hide();
});
</script>

app/views/plays/cpu_turn.html.erb
<h1>CPU Turn</h1>
<div id="your_hand" style="width: 100% !important">
<h2>You</h2>
<p>
  <% if $playerMount.empty? == false %>
  <%= image_tag($playerMount.first.url, width: '300') %>
  <% end %>
</p>
<h4>Deck: <%= $playerMount.length %></h4>
</div>

<div style="text-align: center">
  <a href="/plays/result">CONTINUAR</a>
</div>

<% cpu_plays %>

app/views/plays/result.html.erb
<div id="your_hand">
<h2>You</h2>
<p>
  <% if $playerMount.empty? == false %>
  <%= image_tag($playerMount.first.url, width: '300') %>
  <% end %>
</p>
<h4>Deck: <%= $playerMount.length %></h4>
</div>

<div id="cpu_hand">
  <h2>CPU</h2>
  <p>
    <% if $cpuMount.empty? == false %>
    <%= image_tag($cpuMount.first.url, width: '300') %>
    <% end %>
  </p>
  <h4>Deck: <%= $cpuMount.length %></h4>
</div>


<div style="text-align: center">
  <% if $myTurn %>
  <button id="cpu_turn">CONTINUAR >></button>
  <% else %>
  <button id="your_turn"><< CONTINUAR</button>
  <% end %>
</div>


<script type="text/javascript">
console.log();
  $('#cpu_turn').click(function(){
    console.log('OK');
    $.ajax('/plays/your_request');
    window.location.replace("/plays/cpu_turn");
  });

  $('#your_turn').click(function(){
    $.ajax('/plays/cpu_request');
    window.location.replace("/plays/your_turn");
  });
</script>

app/views/plays/start_game.html.erb
<% start_event %>

<p>
  <a href="/plays/your_turn">START</a>
</p>


<p>
  REGRAS
</p>

<p>
  ....
</p>

app/views/plays/your_turn.html.erb
<h1>Your Turn</h1>


<div id="your_hand" style="width: 100% !important">
<h2>You</h2>
<p>
  <% if $playerMount.empty? == false %>
  <%= image_tag($playerMount.first.url, width: '300') %>
  <br>
  <%= label("", "Força") %>
  <%= radio_button("card", "", $playerMount.first.forca) %>
  <%= label("", "Velocidade") %>
  <%= radio_button("card", "", $playerMount.first.velocidade) %>
  <%= label("", "Habilidade") %>
  <%= radio_button("card", "", $playerMount.first.habilidade) %>
  <%= label("", "Equipamento") %>
  <%= radio_button("card", "", $playerMount.first.equipamento) %>
  <%= label("", "Inteligência") %>
  <%= radio_button("card", "", $playerMount.first.inteligencia) %>

  <% end %>
</p>
<h4>Deck: <%= $playerMount.length %></h4>
</div>
<div style="text-align: center">
  <a href="/plays/result">CONTINUAR</a>
</div>

<% you_play %>